trigger:
- main
- master
- staging/*
- dev/*

pr:
- main
- master

variables:
- group: noos_releases_group_variables

jobs:
- job: Projects
  pool: LocalPool
  steps:
  - checkout: self
    condition: eq(variables.runCondition, true)
    fetchDepth: 50
    submodules: recursive
    clean: true
    persistCredentials: true
  - script: 'python ./build_projects.py $(Build.Repository.LocalPath) $(RELEASE_DIR)'
    condition: eq(variables.runCondition, true)
    displayName: 'Run projects build'
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.Repository.LocalPath)/$(RELEASE_DIR).zip'
      artifact: '$(ARTIFACT_NAME)'
      publishLocation: 'pipeline'